apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-log-viewer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: minikube-log-viewer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minikube-log-viewer
    spec:
      serviceAccountName: sa-logviewer
      volumes:
      - name: logs
        hostPath:
          path: /var/log/containers
      - name: logs-pods
        hostPath:
          path: /var/log/pods
      #for minikube v0.22.2:
      - name: logs-containers-mnt-sda1
        hostPath:
          path: /mnt/sda1/var/lib/docker/containers/
      #for minikube v0.22.3+:
      - name: logs-containers
        hostPath:
          path: /var/lib/docker/containers/
      hostNetwork: true
      containers:
      - name: logviewer
        image: docker.io/ivans3/minikube-log-viewer:latest
        imagePullPolicy: Always
        volumeMounts:
         - name: logs
           mountPath: /var/log/containers/
         - name: logs-pods
           mountPath: /var/log/pods
         - name: logs-containers-mnt-sda1
           mountPath: /mnt/sda1/var/lib/docker/containers/
         - name: logs-containers
           mountPath: /var/lib/docker/containers/

---

apiVersion: v1
kind: Service
metadata:
  name: minikube-log-viewer
  namespace: kube-system
spec:
  ports:
    - port: 3000
      name: http
      nodePort: 32000
  type: NodePort
  selector:
    app: minikube-log-viewer